// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(

      apiKey: "AIzaSyCZF-Cd6CoZvCMo9NFqARDyL0WdXq1FpxE",
      authDomain: "arryv-d.firebaseapp.com",
      projectId: "arryv-d",
      storageBucket: "arryv-d.appspot.com",
      messagingSenderId: "611125770089",
      appId: "1:611125770089:web:54a56a8d15bc7db53faff8",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyBm08IrroljcXSn1uD9DqRlUNtTtE6-kK8",
    appId: "1:611125770089:android:5332a244ab49a8fa3faff8",
    messagingSenderId: "611125770089",
    projectId: "arryv-d",
    storageBucket: "arryv-d.appspot.com",
  );
}
